### ISSUE TITLE
[BUG] recommended posts are without communityId and not a correct json structure

### ISSUE THREAD

**Issue by altanborali16** [altanborali16/SWE574-Group2#170] opened 2024-12-08 11:17 UTC
Hi Yana @kotobusdriver,

I checked your recommendations i am getting output from the postman which is good. I did not check if they are correct or not just assuming they are right, but there are few missing points on recommended posts (for both /post/recommendations-by-tags and /post/recommendations-by-tags  )

Problems are :

1.  Posts does not have communityId in them, for the frontend when we are giving the recommended posts we have design that has a button "Go to community", which I cannot make it run.
2.  When copy paste the output to the [jsonviewer](https://jsonviewer.stack.hu/) I am getting the error : 
![image](https://github.com/user-attachments/assets/00914312-5ee1-4553-8b27-c24c73b590e2)
Which means it will cause me troubles on the frontend mapping.

Here is the output of my json you can also try and inform me.

[
    {
        "id": 12,
        "title": "Test For Loc and Select Template",
        "time": "2024-12-08T08:51:10",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 9,
            "name": "Belt Exam",
            "description": "Belt Exam"
        },
        "postContents": [
            {
                "id": 39,
                "value": "03:55",
                "field": {
                    "id": 27,
                    "name": "Time",
                    "dataType": "TIME"
                }
            },
            {
                "id": 38,
                "value": "2024-12-18",
                "field": {
                    "id": 26,
                    "name": "Date",
                    "dataType": "DATE"
                }
            },
            {
                "id": 40,
                "value": "Inferno",
                "field": {
                    "id": 25,
                    "name": "Location",
                    "dataType": "GEOLOCATION"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 2,
        "title": "Help me",
        "time": "2024-11-25T06:58:11",
        "author": {
            "id": 2,
            "firstname": null,
            "lastname": null,
            "username": "efestrickesback",
            "email": "efe@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 2,
            "name": "Express your feelings",
            "description": "Please express your feelings"
        },
        "postContents": [
            {
                "id": 6,
                "value": "I have so much thing to work on but I just want to lay on my bed or couch, which I do, and with that I loose time and it gives me anxiety. ",
                "field": {
                    "id": 6,
                    "name": "Feelings",
                    "dataType": "TEXT"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 3,
        "title": "DevOps Seminar",
        "time": "2024-11-25T10:09:14",
        "author": {
            "id": 3,
            "firstname": null,
            "lastname": null,
            "username": "Stroggification",
            "email": "feridun@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 3,
            "name": "Online Seminar ",
            "description": "Online Seminar Informations"
        },
        "postContents": [
            {
                "id": 9,
                "value": "www.googlemeets/devopsseminar.com",
                "field": {
                    "id": 7,
                    "name": "Web Link",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 8,
                "value": "I recommend you to book your place :)",
                "field": {
                    "id": 10,
                    "name": "Description",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 10,
                "value": "2025-01-24",
                "field": {
                    "id": 8,
                    "name": "Date",
                    "dataType": "DATE"
                }
            },
            {
                "id": 7,
                "value": "500",
                "field": {
                    "id": 9,
                    "name": "Capacity",
                    "dataType": "TEXT"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 4,
        "title": "Free Frontend Seminar",
        "time": "2024-11-25T11:23:08",
        "author": {
            "id": 3,
            "firstname": null,
            "lastname": null,
            "username": "Stroggification",
            "email": "feridun@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 3,
            "name": "Online Seminar ",
            "description": "Online Seminar Informations"
        },
        "postContents": [
            {
                "id": 13,
                "value": "2024-12-26",
                "field": {
                    "id": 8,
                    "name": "Date",
                    "dataType": "DATE"
                }
            },
            {
                "id": 12,
                "value": "It is a free seminar on front-end design structures",
                "field": {
                    "id": 10,
                    "name": "Description",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 14,
                "value": "www.meetsgoogle/feseminar.com",
                "field": {
                    "id": 7,
                    "name": "Web Link",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 11,
                "value": "1000",
                "field": {
                    "id": 9,
                    "name": "Capacity",
                    "dataType": "TEXT"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 6,
        "title": "29",
        "time": "2024-11-25T15:38:25",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 5,
            "name": "Restaurant Advice",
            "description": "Restaurant Advices with Michelin Star"
        },
        "postContents": [
            {
                "id": 16,
                "value": "Turkish",
                "field": {
                    "id": 13,
                    "name": "Cuisine",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 17,
                "value": "2",
                "field": {
                    "id": 12,
                    "name": "Michelin Star",
                    "dataType": "NUMBER"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 7,
        "title": "Affordable Chickens for Meat Production",
        "time": "2024-11-25T15:52:21",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 7,
            "name": "Chicken For Sale",
            "description": "For chicken selling"
        },
        "postContents": [
            {
                "id": 20,
                "value": "2.9",
                "field": {
                    "id": 19,
                    "name": "Weight",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 19,
                "value": "400",
                "field": {
                    "id": 18,
                    "name": "Number of chickens",
                    "dataType": "NUMBER"
                }
            },
            {
                "id": 18,
                "value": "Mexico",
                "field": {
                    "id": 20,
                    "name": "Country",
                    "dataType": "GEOLOCATION"
                }
            },
            {
                "id": 21,
                "value": "20:40",
                "field": {
                    "id": 21,
                    "name": "Seller Call Available After",
                    "dataType": "TIME"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 10,
        "title": "Backyard Chickens for Sustainable Living",
        "time": "2024-11-25T15:55:49",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 7,
            "name": "Chicken For Sale",
            "description": "For chicken selling"
        },
        "postContents": [
            {
                "id": 30,
                "value": "300",
                "field": {
                    "id": 18,
                    "name": "Number of chickens",
                    "dataType": "NUMBER"
                }
            },
            {
                "id": 32,
                "value": "Brazil",
                "field": {
                    "id": 20,
                    "name": "Country",
                    "dataType": "GEOLOCATION"
                }
            },
            {
                "id": 31,
                "value": "21:00",
                "field": {
                    "id": 21,
                    "name": "Seller Call Available After",
                    "dataType": "TIME"
                }
            },
            {
                "id": 33,
                "value": "2.6 kg",
                "field": {
                    "id": 19,
                    "name": "Weight",
                    "dataType": "TEXT"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 11,
        "title": "Gentle Senior Dog Needs a Home",
        "time": "2024-11-25T15:58:02",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 6,
            "name": "Dogs For Sale",
            "description": "For selling dogs"
        },
        "postContents": [
            {
                "id": 36,
                "value": "2019-11-08",
                "field": {
                    "id": 15,
                    "name": "Birth Date",
                    "dataType": "DATE"
                }
            },
            {
                "id": 34,
                "value": "13",
                "field": {
                    "id": 14,
                    "name": "Age",
                    "dataType": "NUMBER"
                }
            },
            {
                "id": 35,
                "value": "Shih Tzu",
                "field": {
                    "id": 16,
                    "name": "Dog Breed",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 37,
                "value": "400",
                "field": {
                    "id": 17,
                    "name": "Price $",
                    "dataType": "NUMBER"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": [
            {
                "id": 10,
                "time": "2024-12-02T23:48:41",
                "content": "Is is still on sale",
                "author": {
                    "id": 1,
                    "firstname": null,
                    "lastname": null,
                    "username": "altan16",
                    "email": "boralialtan@gmail.com",
                    "authorities": [
                        {
                            "authority": "Visitor"
                        }
                    ],
                    "enabled": true,
                    "accountNonExpired": true,
                    "credentialsNonExpired": true,
                    "accountNonLocked": true
                },
                "replies": [
                    {
                        "id": 11,
                        "time": "2024-12-02T23:49:13",
                        "content": "Yes it is",
                        "author": {
                            "id": 1,
                            "firstname": null,
                            "lastname": null,
                            "username": "altan16",
                            "email": "boralialtan@gmail.com",
                            "authorities": [
                                {
                                    "authority": "Visitor"
                                }
                            ],
                            "enabled": true,
                            "accountNonExpired": true,
                            "credentialsNonExpired": true,
                            "accountNonLocked": true
                        },
                        "replies": []
                    }
                ]
            },
            {
                "id": 11,
                "time": "2024-12-02T23:49:13",
                "content": "Yes it is",
                "author": {
                    "id": 1,
                    "firstname": null,
                    "lastname": null,
                    "username": "altan16",
                    "email": "boralialtan@gmail.com",
                    "authorities": [
                        {
                            "authority": "Visitor"
                        }
                    ],
                    "enabled": true,
                    "accountNonExpired": true,
                    "credentialsNonExpired": true,
                    "accountNonLocked": true
                },
                "replies": []
            }
        ]
    },
    {
        "id": 8,
        "title": "Egg-Laying Chickens Ready For Your Farm",
        "time": "2024-11-25T15:53:33",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 7,
            "name": "Chicken For Sale",
            "description": "For chicken selling"
        },
        "postContents": [
            {
                "id": 23,
                "value": "23:10",
                "field": {
                    "id": 21,
                    "name": "Seller Call Available After",
                    "dataType": "TIME"
                }
            },
            {
                "id": 25,
                "value": "France",
                "field": {
                    "id": 20,
                    "name": "Country",
                    "dataType": "GEOLOCATION"
                }
            },
            {
                "id": 22,
                "value": "560",
                "field": {
                    "id": 19,
                    "name": "Weight",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 24,
                "value": "560",
                "field": {
                    "id": 18,
                    "name": "Number of chickens",
                    "dataType": "NUMBER"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 9,
        "title": "Broiler Chickens in Bulk for Sale",
        "time": "2024-11-25T15:54:54",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 7,
            "name": "Chicken For Sale",
            "description": "For chicken selling"
        },
        "postContents": [
            {
                "id": 27,
                "value": "20:30",
                "field": {
                    "id": 21,
                    "name": "Seller Call Available After",
                    "dataType": "TIME"
                }
            },
            {
                "id": 28,
                "value": "Germany",
                "field": {
                    "id": 20,
                    "name": "Country",
                    "dataType": "GEOLOCATION"
                }
            },
            {
                "id": 29,
                "value": "3.2 kg",
                "field": {
                    "id": 19,
                    "name": "Weight",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 26,
                "value": "980",
                "field": {
                    "id": 18,
                    "name": "Number of chickens",
                    "dataType": "NUMBER"
                }
            }
        ],
        "voteCounter": 0,
        "voters": [],
        "tags": [],
        "comments": []
    },
    {
        "id": 1,
        "title": "AJP İstanbul",
        "time": "2024-11-25T06:33:09",
        "author": {
            "id": 1,
            "firstname": null,
            "lastname": null,
            "username": "altan16",
            "email": "boralialtan@gmail.com",
            "authorities": [
                {
                    "authority": "Visitor"
                }
            ],
            "enabled": true,
            "accountNonExpired": true,
            "credentialsNonExpired": true,
            "accountNonLocked": true
        },
        "template": {
            "id": 1,
            "name": "Event Template",
            "description": "Bjj events on İstanbul"
        },
        "postContents": [
            {
                "id": 2,
                "value": "https://ajptour.com/pictures/t/754492-ftyb/ajp-tour-turkey-national-pro-gi-no-gi-2022.jpg",
                "field": {
                    "id": 5,
                    "name": "Event Poster",
                    "dataType": "IMAGE"
                }
            },
            {
                "id": 3,
                "value": "500",
                "field": {
                    "id": 4,
                    "name": "Price",
                    "dataType": "NUMBER"
                }
            },
            {
                "id": 5,
                "value": "2025-03-15",
                "field": {
                    "id": 2,
                    "name": "Date",
                    "dataType": "DATE"
                }
            },
            {
                "id": 1,
                "value": "Ülker Arena",
                "field": {
                    "id": 1,
                    "name": "Location",
                    "dataType": "TEXT"
                }
            },
            {
                "id": 4,
                "value": "13:00",
                "field": {
                    "id": 3,
                    "name": "Time",
                    "dataType": "TIME"
                }
            }
        ],
        "voteCounter": 1,
        "voters": [
            {
                "id": 53,
                "firstname": null,
                "lastname": null,
                "username": "ash",
                "email": "ash@gmail.com",
                "enabled": true,
                "authorities": [
                    {
                        "authority": "Visitor"
                    }
                ],
                "accountNonExpired": true,
                "credentialsNonExpired": true,
                "accountNonLocked": true,
                "hibernateLazyInitializer"
            }
        ]
    }
]

**Comment by kotobusdriver** [comment] 2024-12-08 14:58
About your point 2: the JSON you posted has this weird-looking standalone "hibernateLazyInitializer" string in the wrong place. When I try it I don't get this. Could it be a mistake you made while copying or editing?

**Comment by kotobusdriver** [comment] 2024-12-08 14:58
About the first point I am opening a pull request.

**Comment by kotobusdriver** [comment] 2024-12-08 19:34
@altanborali16 
Can you please try again from the branch **fix/yana-170-return-communityId-for-recommendations**.

I cannot recreate the issue you are facing, probably due to data related differences between your and my environments. My assumption about the problem is that Jackson has an issue with lazy loaded object references. The JSON you are getting is not even a valid one. 

This latest attempt tries to solve the lazy-loading related issue in another way. Let me know the results.

For more info:
https://stackoverflow.com/questions/41582979/how-to-ignore-handler-hibernatelazyinitializer-in-json-jackson-in-s/44152216#44152216

**Comment by altanborali16** [comment] 2024-12-08 23:39
@kotobusdriver 

For now I am not getting any errors, I tried 3 api's with 2 kind of user, one of them is newly subscribed other one with already took some action.

Also tried other api's if something is affected and from the first view it looks like they are not.

I will try again when subscribed communities and private communities discharged from responses.

**Comment by kotobusdriver** [comment] 2024-12-10 09:26
"subscribed communities discharged from responses" - working on it

**Comment by kotobusdriver** [comment] 2024-12-10 18:46
In case of the recommendations based on likes (both for posts/recommendations-by-likes and community/recommendations endpoints), if the user has not liked any posts, the current implementation automatically tries to provide some posts based on the current logic:

Get the list of all public communities and find top 10 posts from across all of these communities. And add also the most recent 10 posts.

There is a bug in this logic where we get ALL communities. We should rather get the communities where the user has no membership.  This is fixed in pull request https://github.com/altanborali16/SWE574-Group2/pull/179

**Closed** 2024-12-21 16:55 UTC
Labels: bug, Priority : Critical, Component : api, Status : needs review, Status : done
